version: 2.1

executors:
  cpp-executor:
    docker:
      - image: circleci/cpp:latest
    working_directory: ~/project

jobs:
  build:
    executor: cpp-executor
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install SFML Dependencies
          command: sudo apt-get update && sudo apt-get install -y libx11-dev libgl1-mesa-dev libxrandr-dev libudev-dev libfreetype6-dev libjpeg-dev libopenal-dev libflac-dev libvorbis-dev

      # CMake configuration and build
      - run:
          name: CMake Build
          command: |
            mkdir -p cmake-build-debug && cd cmake-build-debug
            cmake -DCMAKE_BUILD_TYPE=Debug ..
            cmake --build .

      # Run tests (if you have any)
      - run:
          name: Run Application
          command: ./bin/2024_project_skipmare

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
