var annotated_dup =
[
    [ "AbstractFactory", "class_abstract_factory.html", "class_abstract_factory" ],
    [ "BGtile", "class_b_gtile.html", "class_b_gtile" ],
    [ "BGtileView", "class_b_gtile_view.html", "class_b_gtile_view" ],
    [ "Bonus", "class_bonus.html", "class_bonus" ],
    [ "BonusView", "class_bonus_view.html", "class_bonus_view" ],
    [ "BoundingBox", "struct_bounding_box.html", "struct_bounding_box" ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "ConcreteFactory", "class_concrete_factory.html", "class_concrete_factory" ],
    [ "DifficultySettings", "class_difficulty_settings.html", "class_difficulty_settings" ],
    [ "DisappearingPlatform", "class_disappearing_platform.html", "class_disappearing_platform" ],
    [ "EASY", "class_e_a_s_y.html", "class_e_a_s_y" ],
    [ "Entity", "class_entity.html", "class_entity" ],
    [ "EntityView", "class_entity_view.html", "class_entity_view" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "HARD", "class_h_a_r_d.html", "class_h_a_r_d" ],
    [ "HorizontalPlatform", "class_horizontal_platform.html", "class_horizontal_platform" ],
    [ "Jetpack", "class_jetpack.html", "class_jetpack" ],
    [ "MEDIUM", "class_m_e_d_i_u_m.html", "class_m_e_d_i_u_m" ],
    [ "Observer", "class_observer.html", "class_observer" ],
    [ "Platform", "class_platform.html", "class_platform" ],
    [ "PlatformView", "class_platform_view.html", "class_platform_view" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "PlayerView", "class_player_view.html", "class_player_view" ],
    [ "Random", "class_random.html", "class_random" ],
    [ "Score", "class_score.html", "class_score" ],
    [ "ScoreView", "class_score_view.html", "class_score_view" ],
    [ "Spring", "class_spring.html", "class_spring" ],
    [ "StaticPlatform", "class_static_platform.html", "class_static_platform" ],
    [ "Stopwatch", "class_stopwatch.html", "class_stopwatch" ],
    [ "Subject", "class_subject.html", "class_subject" ],
    [ "VerticalPlatform", "class_vertical_platform.html", "class_vertical_platform" ],
    [ "World", "class_world.html", "class_world" ]
];