//
// Created by karan on 14/11/2024.
//

#ifndef INC_2024_PROJECT_SKIPMARE_CONCRETEFACTORY_H
#define INC_2024_PROJECT_SKIPMARE_CONCRETEFACTORY_H


class ConcreteFactory {

};


#endif //INC_2024_PROJECT_SKIPMARE_CONCRETEFACTORY_H
