//
// Created by karan on 14/11/2024.
//

#ifndef INC_2024_PROJECT_SKIPMARE_ABSTRACTFACTORY_H
#define INC_2024_PROJECT_SKIPMARE_ABSTRACTFACTORY_H


class AbstractFactory {

};


#endif //INC_2024_PROJECT_SKIPMARE_ABSTRACTFACTORY_H
